### ISSUE TITLE
Newbie Issue I suspect

### ISSUE THREAD

**Issue by Syko80** [ryandaniels/ansible-role-server-update-reboot#2]
This is probably my limited Ansible knowledge but I am getting this error "The field 'environment' has an invalid value, which includes an undefined variable. The error was: 'proxy_env' is undefined.

As per the instructions I understand I need a group variable.  I have created the proxy.yml file as instructed (no proxy);
proxy_env: []

I've created the yml file all over the place to try and debug this!  I have tried,
./etc/ansible/
./etc/ansible/group_vars/
./etc/ansible/group_vars/entos-dev/

My working directory....
~/scripts/
~/scripts/group_vars/
~/scripts/group_vars/centos-dev/

Sorry but any advice!?

**Comment by ryandaniels** [comment]
Try defining the variable in your playbook: 
https://docs.ansible.com/ansible/2.9/user_guide/playbooks_variables.html#defining-variables-in-a-playbook
or right in the command line.
